pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1'
            // Hosts com.microsoft.device.display:display-mask (transitive dep of MSAL)
            name 'Duo-SDK-Feed'
        }
        maven{url "https://repo.opencollab.dev/maven-snapshots"}
        maven{url "https://repo.opencollab.dev/maven-releases"}
    }
}

rootProject.name = "chimeralauncher"
include ':app'
include ':minecraft'
include ':pojav_controls'
